version: 0.0
os: linux
files:
  # Application source code
  - source: /
    destination: /home/ubuntu/app
  # Gunicorn configration
  - source: deployment/gunicorn-config.py
    destination: /home/ubuntu/
  # Gunicorn systemd
  - source: deployment/service/gunicorn.service
    destination: /etc/systemd/system/
  - source: deployment/service/gunicorn.socket
    destination: /etc/systemd/system/

permissions:
  - object: /home/ubuntu/app
    owner: ubuntu
    group: ubuntu
    type:
      - file
      - directory

hooks:
  # http://docs.aws.amazon.com/codedeploy/latest/userguide/reference-appspec-file-structure-hooks.html
  # --- 1 --------------------------
  # You can use this deployment lifecycle event to run tasks on instances before they are deregistered from a load balancer.
  # BeforeBlockTraffic:

  # --- 2 --------------------------
  # During this deployment lifecycle event, internet traffic is blocked from accessing instances that are currently serving traffic.
  # BlockTraffic:

  # --- 3 --------------------------
  # You can use this deployment lifecycle event to run tasks on instances after they are deregistered from a load balancer.
  # AfterBlockTraffic:

  # --- 4 --------------------------
  ApplicationStop:
    - location: deployment/service/stop-app.sh
      timeout: 30

  # --- 5 --------------------------
  # DownloadBundle:
  # (built in step) During this deployment lifecycle event, the AWS CodeDeploy agent copies the application revision files to a temporary location

  # --- 6 --------------------------
  # BeforeInstall:
  # You can use this deployment lifecycle event for preinstall tasks, such as decrypting files and creating a backup of the current version.

  # --- 7 --------------------------
  # Install:
  # (built in step) During this deployment lifecycle event, the AWS CodeDeploy agent copies the revision files from the temporary location to the final destination folder.

  # --- 8 --------------------------
  # You can use this deployment lifecycle event for tasks such as configuring your application or changing file permissions.
  AfterInstall:
    - location: deployment/install-dependecies.sh
      timeout: 50
  # --- 9 --------------------------
  # You typically use this deployment lifecycle event to restart services that were stopped during ApplicationStop.
  ApplicationStart:
    - location: deployment/service/start-app.sh
      timeout: 10
  # --- 10 -------------------------
  # This is the last deployment lifecycle event. It is used to verify the deployment was completed successfully.
  # ValidateService:
  # --- 11 -------------------------
  # You can use this deployment lifecycle event to run tasks on instances before they are registered with a load balancer.
  # BeforeAllowTraffic:
  # --- 12 -------------------------
  # AllowTraffic:
  # (built in step) During this deployment lifecycle event, internet traffic is allowed to access instances after a deployment.
  # --- 13 -------------------------
  # You can use this deployment lifecycle event to run tasks on instances after they are registered with a load balancer.
  # AfterAllowTraffic: